#!/bin/sh -f

/usr/local/SWIG/3.0.2/bin/swig -interface Angpow_swig_py -python -c++ -o ./Angpow_swig_py.icc ./Angpow_swig.i

Python_home=/opt/local/Library/Frameworks/Python.framework/Versions/2.7
Python_lib="-L${Python_home}/lib -lpython2.7"
py_exe="${Python_home}/bin/pythonw"
echo "py_exe:"
echo "${py_exe}"

#Python_home=/usr
#Python_lib="/usr/lib64/libpython2.7.so"

g++ -c -fPIC -I${Python_home}/include/python2.7 -o ./Objs/Angpow_swig_py.o Angpow_swig_py.cc

#-fopenmp
g++ -shared -o Angpow_swig_py.so ./Objs/Angpow_swig_py.o ./Objs/walltimer.o ./Objs/walltime_c.o ${Python_lib}
